CD_URL = "https://cloud.nextcloud/remote.php/dav/"
CD_USERNAME = "cron_epitechcalendar"
CD_PASSWORD = ""
CD_CALENDAR_NAME = "IntraCalendar"
CD_PROJ_CALENDAR_NAME = "IntraProjects"
INTRA_TOKEN = "" # (cookie "user" from intra.epitech.eu)
SYNC_START = "2023-09-01"
SYNC_END = "2024-12-31"
ERR_WEBHOOK_URL = ""